; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv
upload_protocol = esptool
lib_deps = 
	arduino-libraries/Arduino_APDS9960@^1.0.4
	adafruit/Adafruit BusIO@^1.14.1
	adafruit/Adafruit Unified Sensor@^1.1.9
	adafruit/Adafruit BME280 Library@^2.3.0
	paulstoffregen/OneWire@^2.3.7
	milesburton/DallasTemperature@^3.11.0
	csdexter/RDA5807M@^1.0.0
build_flags = 
	-Os
	-DCORE_DEBUG_LEVEL=0
	-DBOARD_HAS_PSRAM=1
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MSC_ON_BOOT=0
	-DARDUINO_USB_DFU_ON_BOOT=0
	-DBOARD_BUILD_FLASH_SIZE=16MB
monitor_filters = 
	esp32_exception_decoder
